#!/usr/bin/env bash
set -euo pipefail

# Pull secrets from Azure Key Vault into .env.local
# Usage: ./scripts/pull-env.sh [--dry-run] [output-file]

VAULT_NAME="shossyworks-vault"
SUBSCRIPTION="bbcd40ae-efb3-4936-bf37-d7e142f003dd"
OUTPUT_FILE="${2:-.env.local}"
DRY_RUN=false

if [[ "${1:-}" == "--dry-run" ]]; then
  DRY_RUN=true
  OUTPUT_FILE="${2:-/dev/stdout}"
fi

# ── Pre-flight checks ──────────────────────────────────────────────
if ! command -v az &> /dev/null; then
  echo "ERROR: Azure CLI (az) not found. Install: https://aka.ms/install-azure-cli" >&2
  exit 1
fi

if ! az account show &> /dev/null; then
  echo "ERROR: Not logged in to Azure. Run: az login" >&2
  exit 1
fi

# ── Secret mapping: vault-name → ENV_VAR_NAME ──────────────────────
# Format: "vault-secret-name:ENV_VAR_NAME"
SECRET_MAP=(
  # Public (client-safe)
  "supabase-url:NEXT_PUBLIC_SUPABASE_URL"
  "supabase-anon-key:NEXT_PUBLIC_SUPABASE_ANON_KEY"
  # Server-only
  "supabase-service-role-key:SUPABASE_SERVICE_ROLE_KEY"
  "supabase-secret-key:SUPABASE_SECRET_KEY"
  "supabase-jwt-secret:SUPABASE_JWT_SECRET"
  "supabase-db-password:SUPABASE_DB_PASSWORD"
  "supabase-direct-connection:DATABASE_URL"
  "supabase-project-id:SUPABASE_PROJECT_ID"
  "supabase-publishable-key:SUPABASE_PUBLISHABLE_KEY"
  "anthropic-api-key:ANTHROPIC_API_KEY"
)

# ── Pull secrets ───────────────────────────────────────────────────
ERRORS=0
OUTPUT=""

OUTPUT+="# ShossyWorks Environment Variables\n"
OUTPUT+="# Generated by scripts/pull-env.sh on $(date -Iseconds)\n"
OUTPUT+="# Source: Azure Key Vault '${VAULT_NAME}'\n\n"

OUTPUT+="# ── Public (client-safe) ──────────────────────────────────\n"
for entry in "${SECRET_MAP[@]}"; do
  VAULT_SECRET="${entry%%:*}"
  ENV_VAR="${entry##*:}"

  VALUE=$(az keyvault secret show \
    --vault-name "$VAULT_NAME" \
    --name "$VAULT_SECRET" \
    --subscription "$SUBSCRIPTION" \
    --query "value" \
    -o tsv 2>/dev/null) || {
    echo "WARNING: Failed to retrieve '${VAULT_SECRET}'" >&2
    ERRORS=$((ERRORS + 1))
    continue
  }

  # Add section header before server-only vars
  if [[ "$ENV_VAR" == "SUPABASE_SERVICE_ROLE_KEY" ]]; then
    OUTPUT+="\n# ── Server-only (NEVER prefix with NEXT_PUBLIC_) ────────\n"
  fi

  OUTPUT+="${ENV_VAR}=${VALUE}\n"
done

# Add local-only vars
OUTPUT+="\n# ── Local dev only ───────────────────────────────────────\n"
OUTPUT+="NEXT_PUBLIC_APP_URL=http://localhost:3000\n"

# ── Write output ───────────────────────────────────────────────────
if [[ "$DRY_RUN" == true ]]; then
  echo -e "$OUTPUT"
  echo ""
  echo "Dry run complete. ${ERRORS} errors."
else
  echo -e "$OUTPUT" > "$OUTPUT_FILE"
  echo "Wrote ${OUTPUT_FILE} (${ERRORS} errors)"
  if [[ $ERRORS -gt 0 ]]; then
    echo "WARNING: Some secrets failed to retrieve. Check output."
    exit 1
  fi
fi
